### ISSUE TITLE
Warnings during build of template

### ISSUE THREAD

**Issue by dsyme** [fsprojects/Fabulous#172] opened 2018-09-07 14:19 UTC
There are two warnings during build of the basic template.  They can be ignored but we should iron them out:

Hi, I'm getting the following 2 errors when following along with the Elmish for XamarinForms getting started. I'm trying to build the dotnet new -i Fabulous.Templates template on visual studio Mac. But when I try to build the dotnet new fabulous-app -lang F# -n SqueakyApp solution I get these errors. Any ideas on how to resolve this? I have the latest DotNet SDK and the latest Visual Studio Mac version.

```
/Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3277: Found conflicts between different versions of "System.Runtime" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. (MSB3277) (SqueakyApp.Android)

/Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Microsoft.Common.CurrentVersion.targets(5,5): Warning MSB3277: Found conflicts between different versions of "Microsoft.CSharp" that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. (MSB3277) (SqueakyApp.Android) (edited)
```

**Comment by TimLariviere** [comment] 2018-10-31 08:55
Conflict with `Microsoft.CSharp` will be fixed by referencing Newtonsoft.Json .NET Standard 2.0 instead of .NET Standard 1.3 (PR ongoing)
The reason is that the former does not have a dependency on Microsoft.CSharp.

 Conflict with `System.Runtime` is another story.
The issue is known and seems to be a MSBuild issue, as well as a Xamarin.Android MSBuild targets issue.
The `app.config` file is ignored by MSBuild only for Xamarin.Android, preventing to use binding redirects to remove the warning.

* [xamarin/xamarin-android#1607 - Found conflicts between different versions of the same dependent assembly](https://github.com/xamarin/xamarin-android/issues/1607)
* [xamarin/xamarin-android#2291 - Xamarin.Android does not support binding redirects](https://github.com/xamarin/xamarin-android/issues/2291)

**Comment by TimLariviere** [comment] 2022-05-16 07:57
Let's ignore those warnings. Soon, we will move to .NET 6.0 anyway

**Closed by TimLariviere** 2022-05-16 07:57 UTC
Labels: t/enhancement, a/templates, s/waiting for external
