### ISSUE TITLE
(Possible) incorrect implementation of ViewElementDataTemplateSelector

### ISSUE THREAD

**Issue by vshapenko** [fsprojects/Fabulous#743] opened 2020-05-17 20:21 UTC
As far as i understood, ViewElementDataTemplateSelector is a direct copy of same XF class.  But there are some differences we should take in mind: 

1. In XF caching is performed by data type, not underlying control type (like Fabulous do). 
2. The meaning of Data template in MVU paradigm looks unknown for me, because we do not do bindings and do not have underlying DataContext objects. as we have in XF,WPF etc.

So i propose that we can use either a new creation of DataTemplate each time (cause we dont do bindings anyway), or use DirectViewElementDataTemplate in ItemsList.

**Comment by TimLariviere** [comment] 2020-05-18 14:15
The thing with ListView/CollectionView is that they have only one DataTemplate (set in `ItemTemplate`) for multiple items (set in `ItemsSource`). So we can't use `DirectViewElementDataTemplate` in lists, since `DirectViewElementDataTemplate` = 1 DataTemplate per ViewElement.

`DirectViewElementDataTemplate` is used by non-list controls that accept a Template to allow on-demand creation. E.g. `ShellContent.ContentTemplate`.

To circumvent this problem, Fabulous uses `ViewElementDataTemplate` that creates an empty row when requested and then listens for `BindingContextChanged` whenever Xamarin.Forms creates a row or reuses it (virtualization when scrolling) so we can apply the correct diffing.

But to create those rows, we have to work with 1 of the 2 XF.DataTemplate constructors.
- `XF.DataTemplate(System.Type)`: We only pass the control type we'd like to instantiate (good for databinding), Xamarin.Forms will use `Activator.CreateInstance` internally - Not usable in Fabulous 
- `XF.DataTemplate(unit -> obj)`: We pass a function that takes no parameter and instantiate the control we'd like ourselves. The problem is that we don't know which data we'll receive. Will it be a View.TextCell, a View.SwitchCell, ... ? We don't know so we can't create the row because the root type will be different.

That's where `ViewElementDataTemplateSelector` comes in.
DataTemplateSelector can wait for Xamarin.Forms requesting a DataTemplate for a specific item.
It will then lazily create (or reuse) the appropriate `ViewElementDataTemplate` for this specific item by inspecting its root control type (by overriding `XF.DataTemplateSelector.OnSelectTemplate(item)`).

It does some caching to avoid creating unnecessary `ViewElementDataTemplate` since a `ViewElementDataTemplate` is not specific to 1 ViewElement, but to the root type of the ViewElement (`ViewElementDataTemplate(System.Type)`).

Behind the scenes when writing
```fs
View.ListView(
    items = [
        View.TextCell()
        View.SwitchCell()
    ]
)
```
Fabulous will transform the items in a `ViewElementHolder[]` and assign it to `ItemsSource`.
https://github.com/fsprojects/Fabulous/blob/3b22759f23fe8727737f3b594071455e5ea4e33a/Fabulous.XamarinForms/src/Fabulous.XamarinForms.Core/CustomControls.fs#L20-L33

The `ViewElementHolder` will then be accessible in the rows' `BindingContext`.
That's why `ViewElementDataTemplate` listens for `BindingContextChanged` to retrieve the `ViewElementHolder` Xamarin.Forms just gave it. It then can call `holder.ViewElement.UpdateIncremental` or `holder.ViewElement.Create` and get the appropriate row content.

**Comment by vshapenko** [comment] 2020-05-18 14:22
@TimLariviere , in #733  there is a problem with virtualization, i guess. First time all is drawn ok, but when container reuse comes in play, things begin to go wrong.

**Comment by TimLariviere** [comment] 2020-05-18 14:26
Writing all this made me realize 2 things.

>In XF caching is performed by data type, not underlying control type (like Fabulous do).

Yes, there might be a conflicting cache reuse at play here.
https://github.com/xamarin/Xamarin.Forms/blob/2a0c7c121b116da09155a52abfefb250f4b9cf9e/Xamarin.Forms.Core/DataTemplateSelector.cs#L18-L20

Xamarin.Forms DataTemplateSelector first tries to get the cached DataTemplate for the item's type when `CachingStrategy` = `ListViewCachingStrategy.RecycleElementAndDataTemplate`.
Though, since Fabulous stores all items as `ViewElementHolder`, it will always get the same DataTemplate from the Xamarin.Forms' cache before calling `ViewElementDataTemplateSelector`.

>So i propose that we can use either a new creation of DataTemplate each time (cause we dont do bindings anyway), or use DirectViewElementDataTemplate

Switching a DataTemplate by another will force Xamarin.Forms to destroy the existing view and recreate it since DataTemplate can't differentially update unlike Fabulous ViewElement.
So I guess our correct usage of `DirectViewElementDataTemplate` is invalid.

**Comment by TimLariviere** [comment] 2020-06-18 17:33
Closing this issue since I explained the reasons behind the implementation of ViewElementDataTemplateSelector, and why we can't use DirectViewElementDataTemplate.
Will focus on the other issues of 0.55-preview.

**Closed by TimLariviere** 2020-06-18 17:33 UTC
