### ISSUE TITLE
Cannot install Fabulous.SkiaSharp

### ISSUE THREAD

**Issue by Happypig375** [fsprojects/Fabulous#439] opened 2019-06-06 09:06 UTC
1. `dotnet new fabulous-app -n "SkiaSharpTesting"`
2. Try to install Fabulous.SkiaSharp 0.35.0
3.
```
Restoring packages for C:\Users\user\source\repos\SkiaSharpTesting\SkiaSharpTesting\SkiaSharpTesting.fsproj...


Attempting to gather dependency information for package 'Fabulous.SkiaSharp.0.35.0' with respect to project 'SkiaSharpTesting.iOS', targeting 'Xamarin.iOS,Version=v1.0'
Gathering dependency information took 6.87 sec
Attempting to resolve dependencies for package 'Fabulous.SkiaSharp.0.35.0' with DependencyBehavior 'Lowest'
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'Xamarin.Essentials 1.0.0 constraint: System.Numerics.Vectors (>= 4.5.0)'
Resolving dependency information took 0 ms
Resolving actions to install package 'Fabulous.SkiaSharp.0.35.0'
Resolved actions to install package 'Fabulous.SkiaSharp.0.35.0'


Attempting to gather dependency information for package 'Fabulous.SkiaSharp.0.35.0' with respect to project 'SkiaSharpTesting.Android', targeting 'MonoAndroid,Version=v8.1'
Gathering dependency information took 7.79 sec
Attempting to resolve dependencies for package 'Fabulous.SkiaSharp.0.35.0' with DependencyBehavior 'Lowest'
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'Xamarin.Forms 4.0.0.425677 constraint: Xamarin.Android.Support.v4 (>= 28.0.0.1)', 'Xamarin.Forms 4.0.0.425677 constraint: Xamarin.Android.Support.Design (>= 28.0.0.1)', 'Xamarin.Forms 4.0.0.425677 constraint: Xamarin.Android.Support.v7.AppCompat (>= 28.0.0.1)', 'Xamarin.Forms 4.0.0.425677 constraint: Xamarin.Android.Support.v7.CardView (>= 28.0.0.1)', 'Xamarin.Forms 4.0.0.425677 constraint: Xamarin.Android.Support.v7.MediaRouter (>= 28.0.0.1)', 'Xamarin.Forms 4.0.0.425677 constraint: Xamarin.Android.Support.CustomTabs (>= 28.0.0.1)', 'Xamarin.Essentials 1.0.0 constraint: System.Numerics.Vectors (>= 4.5.0)'
Resolving dependency information took 0 ms
Resolving actions to install package 'Fabulous.SkiaSharp.0.35.0'
Resolved actions to install package 'Fabulous.SkiaSharp.0.35.0'
Adding package 'SkiaSharp.1.60.3' to folder 'C:\Users\hadri\source\repos\SkiaSharpTesting\packages'
Added package 'SkiaSharp.1.60.3' to folder 'C:\Users\hadri\source\repos\SkiaSharpTesting\packages'
Install failed. Rolling back...
Package 'SkiaSharp.1.60.3' does not exist in project 'SkiaSharpTesting.iOS'
Removing package 'SkiaSharp.1.60.3' from folder 'C:\Users\hadri\source\repos\SkiaSharpTesting\packages'
Removed package 'SkiaSharp.1.60.3' from folder 'C:\Users\hadri\source\repos\SkiaSharpTesting\packages'
Executing nuget actions took 4.59 sec
Failed to add reference to 'SkiaSharp'.
  Object reference not set to an instance of an object.
Time Elapsed: 00:00:20.3082912
========== Finished ==========
```

**Comment by Happypig375** [comment] 2019-06-06 09:08
Also reproducible with F# iOS Single View App -> Add SkiaSharp
```


Attempting to gather dependency information for package 'SkiaSharp.Views.Forms.1.68.0' with respect to project 'SkiaSharpFSharp', targeting 'Xamarin.iOS,Version=v1.0'
Gathering dependency information took 22.1 sec
Attempting to resolve dependencies for package 'SkiaSharp.Views.Forms.1.68.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'SkiaSharp.Views.Forms.1.68.0'
Resolved actions to install package 'SkiaSharp.Views.Forms.1.68.0'
  GET https://api.nuget.org/v3-flatcontainer/xamarin.forms/3.3.0.912540/xamarin.forms.3.3.0.912540.nupkg
Adding package 'SkiaSharp.1.68.0' to folder 'C:\Users\hadri\source\repos\SkiaSharpFSharp\packages'
  OK https://api.nuget.org/v3-flatcontainer/xamarin.forms/3.3.0.912540/xamarin.forms.3.3.0.912540.nupkg 775ms
Installing Xamarin.Forms 3.3.0.912540.
Added package 'SkiaSharp.1.68.0' to folder 'C:\Users\hadri\source\repos\SkiaSharpFSharp\packages'
Install failed. Rolling back...
Package 'SkiaSharp.1.68.0' does not exist in project 'SkiaSharpFSharp'
Removing package 'SkiaSharp.1.68.0' from folder 'C:\Users\hadri\source\repos\SkiaSharpFSharp\packages'
Removed package 'SkiaSharp.1.68.0' from folder 'C:\Users\hadri\source\repos\SkiaSharpFSharp\packages'
Executing nuget actions took 6.58 sec
Failed to add reference to 'SkiaSharp'.
  Parameter cannot be null.
  Parameter name: project
Time Elapsed: 00:00:29.3461112
========== Finished ==========


```

**Comment by Happypig375** [comment] 2019-06-06 09:12
Anyone know if this is a NuGet or Xamarin issue?

**Comment by Happypig375** [comment] 2019-06-06 09:29
--> NuGet/Home#8205

**Comment by TimLariviere** [comment] 2019-07-12 14:47
I don't reproduce on Visual Studio for Mac 8.1.5 / Fabulous 0.41

**Comment by Happypig375** [comment] 2019-07-15 09:33
I'm still reproing though.
<details>
<summary>Log</summary>

```
Restoring packages for C:\Users\Admin\source\repos\SwitchingPagesHugeBug\SwitchingPagesHugeBug.UWP\SwitchingPagesHugeBug.UWP.csproj...


Attempting to gather dependency information for package 'Fabulous.XamarinForms.SkiaSharp.0.41.0' with respect to project 'SwitchingPagesHugeBug.iOS', targeting 'Xamarin.iOS,Version=v1.0'
Gathering dependency information took 12.14 sec
Attempting to resolve dependencies for package 'Fabulous.XamarinForms.SkiaSharp.0.41.0' with DependencyBehavior 'Lowest'
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'Xamarin.Essentials 1.1.0 constraint: System.Numerics.Vectors (>= 4.5.0)'
Resolving dependency information took 0 ms
Resolving actions to install package 'Fabulous.XamarinForms.SkiaSharp.0.41.0'
Resolved actions to install package 'Fabulous.XamarinForms.SkiaSharp.0.41.0'


Attempting to gather dependency information for package 'Fabulous.XamarinForms.SkiaSharp.0.41.0' with respect to project 'SwitchingPagesHugeBug.Android', targeting 'MonoAndroid,Version=v9.0'
Gathering dependency information took 17.51 sec
Attempting to resolve dependencies for package 'Fabulous.XamarinForms.SkiaSharp.0.41.0' with DependencyBehavior 'Lowest'
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'Xamarin.Android.Support.Loader 28.0.0.1 constraint: Xamarin.Android.Arch.Lifecycle.LiveData (= 1.1.1.1)', 'Xamarin.Essentials 1.1.0 constraint: System.Numerics.Vectors (>= 4.5.0)'
Resolving dependency information took 0 ms
Resolving actions to install package 'Fabulous.XamarinForms.SkiaSharp.0.41.0'
Resolved actions to install package 'Fabulous.XamarinForms.SkiaSharp.0.41.0'
Adding package 'SkiaSharp.1.60.3' to folder 'C:\Users\Admin\source\repos\SwitchingPagesHugeBug\packages'
Added package 'SkiaSharp.1.60.3' to folder 'C:\Users\Admin\source\repos\SwitchingPagesHugeBug\packages'
Added package 'SkiaSharp.1.60.3' to 'packages.config'
Successfully installed 'SkiaSharp 1.60.3' to SwitchingPagesHugeBug.iOS
Adding package 'SkiaSharp.Views.1.60.3' to folder 'C:\Users\Admin\source\repos\SwitchingPagesHugeBug\packages'
Added package 'SkiaSharp.Views.1.60.3' to folder 'C:\Users\Admin\source\repos\SwitchingPagesHugeBug\packages'
Added package 'SkiaSharp.Views.1.60.3' to 'packages.config'
Successfully installed 'SkiaSharp.Views 1.60.3' to SwitchingPagesHugeBug.iOS
Adding package 'SkiaSharp.Views.Forms.1.60.3' to folder 'C:\Users\Admin\source\repos\SwitchingPagesHugeBug\packages'
Added package 'SkiaSharp.Views.Forms.1.60.3' to folder 'C:\Users\Admin\source\repos\SwitchingPagesHugeBug\packages'
Added package 'SkiaSharp.Views.Forms.1.60.3' to 'packages.config'
Successfully installed 'SkiaSharp.Views.Forms 1.60.3' to SwitchingPagesHugeBug.iOS
Adding package 'Fabulous.XamarinForms.SkiaSharp.0.41.0' to folder 'C:\Users\Admin\source\repos\SwitchingPagesHugeBug\packages'
Added package 'Fabulous.XamarinForms.SkiaSharp.0.41.0' to folder 'C:\Users\Admin\source\repos\SwitchingPagesHugeBug\packages'
Added package 'Fabulous.XamarinForms.SkiaSharp.0.41.0' to 'packages.config'
Successfully installed 'Fabulous.XamarinForms.SkiaSharp 0.41.0' to SwitchingPagesHugeBug.iOS
Executing nuget actions took 11.13 sec
Package 'SkiaSharp.1.60.3' already exists in folder 'C:\Users\Admin\source\repos\SwitchingPagesHugeBug\packages'
Install failed. Rolling back...
Package 'SkiaSharp.1.60.3' does not exist in project 'SwitchingPagesHugeBug.Android'
Executing nuget actions took 6.13 sec
Failed to add reference to 'SkiaSharp'.
  Object reference not set to an instance of an object.
Time Elapsed: 00:00:48.2342821
========== Finished ==========
```
</details>

<details>
<summary>Environment info</summary>

```
Microsoft Visual Studio Community 2019
Version 16.1.5
VisualStudio.16.Release/16.1.5+29025.244
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA419
Microsoft Visual C++ 2019

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

Application Insights Tools for Visual Studio Package   9.1.00429.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.1.429.50124
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.1.429.50124
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.1.429.50124
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.3.9000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Stream Analytics Tools for Visual Studio   2.3.9000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.1.77 (master@24013d5)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure HDInsight Azure Node   2.3.9000.0
HDInsight Node under Azure Node

Microsoft Azure Hive Query Language Service   2.3.9000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.3.9000.0
Language service for Azure Stream Analytics

Microsoft Azure Stream Analytics Node   1.0
Azure Stream Analytics Node under Azure Node

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20419.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Mono Debugging for Visual Studio   16.1.1 (2473f22)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   5.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61904.23160
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   16.0.10506.2004
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.1.0-beta.19253.3+42526fe359672a05fd562dc16a91a43d0fe047a7
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

Visual Studio Tools for Unity   4.1.1.0
Visual Studio Tools for Unity

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.1.0.545 (d16-1@db7c858e8)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.1.0.418 (remotes/origin/d16-1@5b958bb10)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.2.112 (4db4af4)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.3.0.23 (HEAD/d0b48056f)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: mono/mono/2018-08@3a07bd426d3
    Java.Interop: xamarin/java.interop/d16-1@5ddc3e3
    LibZipSharp: grendello/LibZipSharp/d16-1@44de300
    LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.27.1@8212a2d
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-1@acabd26


Xamarin.iOS and Xamarin.Mac SDK   12.10.0.157 (6bd9475)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```
</details>

**Comment by Happypig375** [comment] 2019-07-15 09:33
Might be a Windows-only issue.

**Comment by Happypig375** [comment] 2019-07-15 09:35
And an Android-project-only issue.

**Comment by Happypig375** [comment] 2019-07-16 11:38
As of Fabulous 0.41.0, I cannot even install the Fabulous nuget package.
```


Attempting to gather dependency information for package 'Fabulous.0.41.0' with respect to project 'PanaIoTApp.iOS', targeting 'Xamarin.iOS,Version=v1.0'
Gathering dependency information took 15.99 sec
Attempting to resolve dependencies for package 'Fabulous.0.41.0' with DependencyBehavior 'Lowest'
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'Fabulous.Core 0.36.0 constraint: Xamarin.Forms (>= 4.0.0.425677)', 'Fabulous.CustomControls 0.36.0 constraint: Xamarin.Forms (>= 4.0.0.425677)', 'OxyPlot.Xamarin.Forms 1.1.0-unstable0011 constraint: Xamarin.Forms (>= 2.3.3.180)', 'SkiaSharp.Views.Forms 1.68.0 constraint: Xamarin.Forms (>= 3.3.0.912540)'
Resolving dependency information took 0 ms
Resolving actions to install package 'Fabulous.0.41.0'
Resolved actions to install package 'Fabulous.0.41.0'


Attempting to gather dependency information for package 'Fabulous.0.41.0' with respect to project 'PanaIoTApp.Android', targeting 'MonoAndroid,Version=v9.0'
Gathering dependency information took 13.53 sec
Attempting to resolve dependencies for package 'Fabulous.0.41.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Fabulous.0.41.0'
Resolved actions to install package 'Fabulous.0.41.0'
Adding package 'Fabulous.0.41.0' to folder 'C:\Users\Admin\source\repos\Panasonic IoT App\packages'
Added package 'Fabulous.0.41.0' to folder 'C:\Users\Admin\source\repos\Panasonic IoT App\packages'
Install failed. Rolling back...
Package 'Fabulous.0.41.0 : FSharp.Core [4.6.2, )' does not exist in project 'PanaIoTApp.iOS'
Removing package 'Fabulous.0.41.0 : FSharp.Core [4.6.2, )' from folder 'C:\Users\Admin\source\repos\Panasonic IoT App\packages'
Removed package 'Fabulous.0.41.0 : FSharp.Core [4.6.2, )' from folder 'C:\Users\Admin\source\repos\Panasonic IoT App\packages'
Executing nuget actions took 1.08 sec
Failed to add reference to 'Fabulous'.
  Object reference not set to an instance of an object.
Time Elapsed: 00:00:31.0566449
========== Finished ==========
```

**Comment by TimLariviere** [comment] 2019-07-16 12:08
It complains about Fabulous.Core.
Could you try to remove all Fabulous packages from your iOS project first, then add the new v0.41 package?

**Comment by TimLariviere** [comment] 2020-06-18 18:47
Closing since this is a NuGet issue and not a Fabulous one. Please refer to the linked NuGet issue instead.

**Closed by TimLariviere** 2020-06-18 18:47 UTC
Labels: s/waiting for external, t/bug
