### ISSUE TITLE
Unit testing `Cmd.ofAsyncMsg`

### ISSUE THREAD

**Issue by ghost** [fsprojects/Fabulous#283] opened 2019-01-18 03:42 UTC
My team is working on an app using `Fabulous` framework, and we want to create *unit tests* for each module (not just the root view, update, but children as well) that will test the business logic of the application. But there seem to be certain limitations around testing `Cmd`s, especially no simple work around seems to be available for commands created with `Cmd.ofAsyncMsg`.

Update:
It feels like the right way to test is to create a separate program for each module that is tested and run the program, but it seems like this is **to big** of a setup and using a simple `Cmd` primitive could still be useful.

The main issue with this approach is that in order to get the update loop going we need to create a `ProgrammRunner`, which takes in an instance of a `Xamarin.Forms.Application`, which in our setup we don't want to have `Xamarin.Forms` as a dependency at all. Keep in mind the tests will be run in the host environment, Windows `x86_64`.

Our setup (`FsUnit + xUnit`)
* Shared (Fabulous here)
* Android / iOS
* Shared.Test

What we were able to implement:
```F#
Module.update (Module.Msg.EntryChanged "lol") initModel
  |> fst
  |> should equal "lol"
```

What we need:
```F#
let customDispatch = function
      Ok result -> should be true
      Error error -> failwith "async command failed")
Module.update Module.Msg.SavePressed initModel
  |> snd
  |> Cmd.dispatch customDispatch
```

My questions: 
1. Are there any suggestions about how this custom custom dispatch should be implemented? Am I even taking the right approach to unit testing a `Fabulous` app?
3. Functional programming is unit test - friendly, also any modern application will issue a lot of `async` operations, so why does not `Fabulous` does not talk about it in its documentation as well as does not provide some primitives for doing this type of testing (I might just be a noob that did not read the docs carefully lol :D )

Primitive API proposal for (3):
```F#
// create Cmd's queue
Cmd.ofAsynMsg (HttpGet "http://fsharp.com")
  // dispatch Cmd using custom primitive (this one will wait for all commands to produce a message)
  |> Cmd.dispatch ProgramDispatch<Msg>.TestSynchronousDispatch
  // this test will then verify that the commands indeed resolved to the right messages
  |> should equal [ (Ok "responseBody") ]
```

ps. Thanks for the framework!

**Comment by TimLariviere** [comment] 2019-01-19 08:30
@kirillpadx I'm glad to hear that you and your team are using Fabulous. :)

We're lacking on the documentation, especially regarding unit testing.
So it's definitely something we'll work on in the future.

Thanks for the proposal.
Having the ability to use a custom dispatch for testing will be extremely useful.
We might need to put it in a different module dedicated to testing, to avoid confusion.

Still need to check the feasibility of`ProgramDispatch<Msg>.TestSynchronousDispatch` though. (ofAsyncMsgOption could be a problem)
And we will certainly need a better naming too :)

**Comment by kirillpadx** [comment] 2019-01-21 20:04
@TimLariviere, happy to hear my suggestion makes sense, and I do hope my naming will not be used!

I am not sure that a custom dispatch function is even the best way to go about testing a `Fabulous` app. A more elegant solution would be to implement a new type of `ProgramRunner` something like 
```F#
type [InitUpdate | Test]ProgramRunner<'model, 'msg>(program: Program<'model, 'msg, 'freeTypeVariable>)
```
that will not have `Xamarin` as a dependency (like `Application`, `Device`). Combined with some way of running the program until it `halts` (no more messages to process, and no `async` computations running) the test results can be nicely `folded` into the top-level model. 

This is the current ~~pretty ugly~~ very ugly work around I got to work, just posting it here in case someone is having similar issues, but does not want to wait for the official solution. This looks a little dirty, but well, it works 💃 

```F#        
[<Fact>]
let ``async test`` () =
    let mutable sharedState= false
    let lock = new AutoResetEvent(false)

    let validMockUser = "kirill@padxchange.com"
    let mockDelegate = function
        | SaveSuccess savedUser ->
            validMockUser= savedUser
        | _ -> false
    let model, _ = User.init validMockUser mockDelegate

    // this call returns async Cmd that will do some IO
    let _, asyncCmd = User.update SavePressed model
    Cmd.dispatch (fun testResult-> 
            sharedState<- testResult
            lock.Set() |> ignore
        )
        asyncCmd
    lock.WaitOne(millisecondsTimeout = 1000) |> ignore
            
    // FsUnit syntax used here
    success |> should equal true
```

**Comment by TimLariviere** [comment] 2019-01-22 09:17
If I understand correctly, there's 2 things in this issue?
- Add the ability to unit test `Cmd`
- Add the ability to do integration testing of the whole `Program`

**Comment by kirillpadx** [comment] 2019-01-22 19:01
Yes

**Comment by TimLariviere** [comment] 2019-01-29 18:55
I'm currently facing the issue of `Cmd.ofAsyncMsg` being untestable in #296
The way I ended up doing this is more or like @kirillpadx's solution.

```fsharp
let execute (cmd: Cmd<'msg>) : 'msg list =
    let internalDispatch (r: Ref<'msg option>) (semaphore: System.Threading.AutoResetEvent) msg =
        r.Value <- Some msg
        semaphore.Set() |> ignore

    [ for sub in cmd do
        let result = ref None
        use semaphore = new System.Threading.AutoResetEvent(false)
        dispatch (internalDispatch result semaphore) cmd
        semaphore.WaitOne() |> ignore
        yield result.Value.Value ]
```

Code to test:
```fsharp
let timerCmd () = 
    async { do! Async.Sleep 200
            return TimedTick }
    |> Cmd.ofAsyncMsg

let update msg model =
    match msg with
    | TimerToggled on -> { model with TimerOn = on }, (if on then timerCmd() else Cmd.none)
```

Usage:
```fsharp
[<Test>]
let ``Given the message TimerToggled true, Update should enable the timer and return a new TimerCmd``() =
    let initialModel = { Count = 5; Step = 4; TimerOn = false }
    let expectedModel = { Count = 5; Step = 4; TimerOn = true }
    let expectedCommandMsg = [ TimedTick ]

    let actualModel, actualCmd = App.update (TimerToggled true) initialModel
    let actualCommandMsg = Cmd.execute actualCmd

    actualModel |> should equal expectedModel
    actualCommandMsg |> should equal expectedCommandMsg
```

**Comment by TimLariviere** [comment] 2019-01-29 18:59
The problem is that there's no way to tell a `Cmd<'msg>` is asynchronous.
The signature is only `('msg -> unit) -> unit`

So for now, with impacting Fabulous, the correct way is to wait until the Cmd dispatched. (in case it would be asynchronous).

But this has a major flow. `Cmd.ofMsgOption` and `Cmd.ofAsyncMsgOption` might end up locking the thread indefinitely, as they might never dispatch a message.

**Comment by TimLariviere** [comment] 2019-06-07 09:28
Fixed with the CmdMsg pattern. See #418

**Closed by TimLariviere** 2019-06-07 09:28 UTC
Labels: enhancement, unit testing
