### ISSUE TITLE
Elements multiplied after pressing a button

### ISSUE THREAD

**Issue by kerams** [fsprojects/Fabulous#343] opened 2019-02-21 19:00 UTC
Using the SqueakyApp template (v0.32) I built an APK in release mode without making any code changes and installed it on a Onyx Boox Note device (Android 6.0.1). When I press any of the 3 buttons for the first time all of the elements multiply and appear below the original set. It looks like this:

![img_20190221_195253](https://user-images.githubusercontent.com/5063478/53194237-25533780-3613-11e9-8304-669d709e0e92.jpg)

**Comment by TimLariviere** [comment] 2019-02-21 22:22
@kerams I can't reproduce it. (Android 6.0 / tablet emulator)
Is it specific to this device?

**Comment by kerams** [comment] 2019-02-22 07:08
I suppose it is. Do you have any tips where to insert logging to get to the bottom of this?

**Comment by kerams** [comment] 2019-02-22 07:21
Now, I don't know the internals of Fabulous, but is it any similar to Fable/React in terms of updating only the parts of the screen which have changed (by doing some diffing behind the scenes)? I have a feeling there could be something funny going on around those parts.

**Comment by TimLariviere** [comment] 2019-02-23 08:23
>Now, I don't know the internals of Fabulous, but is it any similar to Fable/React in terms of updating only the parts of the screen which have changed (by doing some diffing behind the scenes)? I have a feeling there could be something funny going on around those parts.

Yes, seems like it. But it's strange to only see it on this device. The same codebase is shared on more than 6 platforms...

>I suppose it is. Do you have any tips where to insert logging to get to the bottom of this?

You can use `Program.withConsoleTrace` (https://fsprojects.github.io/Fabulous/logging.html).
Also Fabulous prints by default in debug output saying when a new control is created.

Other than that, if you can test the CounterApp sample of this repository on your device, maybe take a look at this code below. It's where Fabulous decides if it should reuse a control or create a new one.
https://github.com/fsprojects/Fabulous/blob/e8231902a6cd9b08602e5a9f0dbf87e5dd2b7ef1/src/Fabulous.Core/ViewConverters.fs#L229-L236

**Comment by kerams** [comment] 2019-02-23 08:46
I'll definitely take a look at that, thanks. What I've found earlier with a minimal repro:

```fsharp
type Model = unit

type Msg = Nothing

let init () = (), []

let update Nothing model = model, []

let view model dispatch =
    View.ContentPage(
        content = View.ListView(verticalOptions = LayoutOptions.Center,
        items = [ 
            View.Button(text = "Increment", horizontalOptions = LayoutOptions.Center, command = fun () -> dispatch Nothing)
            View.Label(text = "Wtf", horizontalOptions = LayoutOptions.Center)
            View.Label(text = "wtf2", horizontalOptions = LayoutOptions.Center)

        ]))

let program = Program.mkProgram init update view
```

It does not matter if I use a `ListView` or a `StackLayout`, when I press the button for the first time, all of the child items (except the first one!) are duplicated.

**Comment by kerams** [comment] 2019-02-23 11:09
Ok, I'm onto something. The problem manifests itself in CounterApp when using Release configuration, not Debug.

**Comment by kerams** [comment] 2019-02-23 13:13
I must be trippin', this is what I found, first screenshot Release, second Debug.

![devenv_bwlumwlklu](https://user-images.githubusercontent.com/5063478/53286884-f8b73100-3774-11e9-88c6-fc990974e097.png)

![devenv_jqdeqphrtx](https://user-images.githubusercontent.com/5063478/53286887-fb198b00-3774-11e9-936a-b16cb2e85c90.png)

I'm inclined to close this issue. It seems I'm potentially dealing with some Mono bug. No idea how to continue diagnosing this further though...

**Comment by kerams** [comment] 2019-02-24 12:44
@TimLariviere This is reproducible in an emulator, but it needs to run emulated armeabi-v7a, not x86.

**Comment by TimLariviere** [comment] 2019-02-25 08:34
@kerams That's an impressive bug you found. 😮 

Maybe we can change the code somehow to prevent this to happen?
`n` seems to be corrupted at one point, would another variable be impacted as well?

It would be a nasty workaround, but we can't do much more I'm afraid.

**Comment by kerams** [comment] 2019-02-25 09:35
I'll play around with that variable a little. Also, perhaps @dsyme would be kind enough to spare a moment and share his opinion? It does not look like an F# optimization bug, because I don't see anything out of the ordinary in the decompiled binary. So maybe Mono is to blame? I'm afraid I don't have the knowledge to pursue this deeper.

**Comment by dsyme** [comment] 2019-02-26 00:37
It does look like a Mono JIT bug... Ouch....  

I don't think it's an F# compiler bug (https://sharplab.io might help there)

There is likely a simple adjustment to the F# code that would avoid the bug.

Don't close the bug, as we should both report this to the Mono repo and add a workaround to Fabulous

**Comment by kerams** [comment] 2019-02-26 11:34
Doing:
```
let n' = targetColl.Count
let n = targetColl.Count
```

Seems to do the trick. `n'` gets corrupted, but `n` is fine. @TimLariviere, are you ok with this hotfix?

**Comment by TimLariviere** [comment] 2019-02-26 18:13
@kerams With a good comment next to `n'` explaining why we are doing this, I'm good with this.

**Comment by TimLariviere** [comment] 2019-03-11 12:05
@kerams Is your problem still fixed with the released v0.33.1?
Do you want to report this bug to https://github.com/mono/mono , or should we do it?

**Comment by kerams** [comment] 2019-03-11 15:43
Yes, I've created a fresh project from the updated template and I see no problems.

Please, report it yourselves. I would not even know how to create a reasonable repro for an issue like this.

**Comment by Happypig375** [comment] 2019-07-02 09:34
![image](https://user-images.githubusercontent.com/19922066/60502002-8c82a600-9cef-11e9-82d4-0f42d69460a5.png)
Ehm?

**Comment by kerams** [comment] 2019-07-02 10:56
The exception is thrown on line 156?

**Comment by Happypig375** [comment] 2019-07-02 11:13
Yes

**Comment by Happypig375** [comment] 2019-07-02 11:16
Not reproducible on x86 emulator, but my arm device (Redmi 6) threw this nullref exception.

**Comment by kerams** [comment] 2019-07-02 12:04
n holds the original length, but there are inserts into targetColl on line 166, so that's to be expected.
This almost looks like coll refers to a different place in memory on the second iteration. More fishy ARM business.

**Comment by Happypig375** [comment] 2019-07-02 12:06
When I hover over `coll`, it's an array of length 13. The debugger tells me it's not null. (`coll.Length` is 13 in above screenshot.)

**Comment by TimLariviere** [comment] 2019-07-24 10:32
@Happypig375 Could you try to create a value on line 147
```
let collLength = coll.Length;
```
And then use this value instead of `coll.Length` in all places

Does it solve your issue?

**Closed** 2020-02-10 13:41 UTC
Labels: external/bug, proj/xamarinforms
