### ISSUE TITLE
LiveUpdate (fscd.exe) doesn't detect saving of file in Visual Studio 2017 (Windows Edition)

### ISSUE THREAD

**Issue by DieselMeister** [fsprojects/Fabulous#141] opened 2018-07-25 20:17 UTC
Problem: The fscd.exe do not detect a saving of a file in Visual Studio 2017 (Windows).

The file is recognized by the watcher.

Other editors like notpad++ or Visual Studio Code are working. The saving will be detected.

I am currently use the newest version of Visual Studio 2017 (15.7.5).

**Comment by slang25** [comment] 2018-07-25 22:35
Confirmed here too

**Comment by dsyme** [comment] 2018-10-17 20:03
This is really odd, it always works for me.

**Comment by dsyme** [comment] 2018-10-17 20:03
I've never noticed it miss the save of a file...

**Comment by TimLariviere** [comment] 2018-12-11 18:38
Should be fixed by #247

**Closed by TimLariviere** 2018-12-11 18:38 UTC
Labels: needs repro
