### ISSUE TITLE
View update function called continuously

### ISSUE THREAD

**Issue by sandeepc24** [fsprojects/Fabulous#554] opened 2019-08-24 10:22 UTC
I have an issue where view function is called continuously  when the view is shown second time. I have not been able to recreate this issue in a separate app but attached is a movie showing the issue.
![2019-08-24_22-30-53](https://user-images.githubusercontent.com/4897654/63636103-e768c600-c6be-11e9-9d2b-90e7e964517b.gif)

**Comment by sandeepc24** [comment] 2019-08-24 10:52
This behaviour is only visible if debounce is used, if I remove debounce then flickering goes away.

**Comment by sandeepc24** [comment] 2019-08-24 11:13
Other thing I have noticed is the textChanged event is fired on init, this should not happen.

**Comment by TimLariviere** [comment] 2019-08-28 07:25
@sandeepc24 Is it specific to UWP or does it happen on other platforms as well?

**Comment by sandeepc24** [comment] 2019-08-28 09:03
I have only tested it on Android and it happens on Android as well.

**Comment by Blener** [comment] 2019-09-20 03:26
I've this issue too, whenever I try to reload a page some text fields do that. What worked for me was to first load the page without the Text Changed event attached. I got the idea from FabScaffold, something like (code from [here](https://github.com/kunjee17/FabScaffold/blob/dda1f84f850a5d8a96fc0081ffa2490c07f2f185/FabScaffold/Application/AddOrEditPerson.fs#L160)): 
`let attachChange (condition) (changeEvent) =
        if condition then debounce DebounceNo changeEvent |> Some
        else None`

I only tested in Android.

**Comment by TimLariviere** [comment] 2019-09-20 06:36
Can't reproduce from the gif. Seems like something particular is triggering the issue.

@Blener Would you be able to share your app, or a sample that exhibits this issue?

**Comment by Blener** [comment] 2019-09-20 14:44
@TimLariviere I understood the problem while reproducing it [here](https://github.com/Blener/fabulous-bug). The problem in my case can be reproduced like this:
When the user ask to load something, I set the page to empty values and dispatch a Cmd that access the database and return a Msg with the actual data. The Msg update the page with the actual data and that's when it start the infinite loop of (Msg "") and (Msg "value") dispatches.

**Comment by sandeepc24** [comment] 2019-09-20 22:45
I think we need to resolve this issue as I am seeing this issue in another app at work. It does db calls and then ends up in a loop.

I have tried recreating this issue in another app but so far haven't had much success.

**Comment by SergejDK** [comment] 2019-09-21 08:10
@sandeepc24 and @Blener 
Can you give me some data: 
Androidversion
Visual Studio version
Etc. 

I want to reproduce as good as possible.

**Comment by Blener** [comment] 2019-09-21 16:08
@SergejDK sure. 
I'm using JetBrains Rider 2019.2.2, I runned the app using the emulator with a Nexus 5X image on Android 8.1 (API 27). I also tried it on a Nexus 10 Tablet emulator image on Android 6.0 (API 23). On both I get the flickering issue. Everything is running on Windows 10.

Anything else I can help just let me know.

**Comment by SergejDK** [comment] 2019-10-01 20:35
@TimLariviere and a little status update
we definetly have something going on with the debounce function. 

So the thing I found out is that using higher numbers e.g. 5000 in debounce will recreate the issue for me.  Lower values like 250 are okay and worked. 

I could recreate it with VS4Mac and my device and emulator.

Maybe we should check if we use the 'Device.StartTimer' correct. 

@sandeepc24 
Can you maybe tell me what you set your debounce to? And maybe try a smaller value just to confirm me.

**Comment by sandeepc24** [comment] 2019-10-03 08:48
Hi @SergejDK , I am using 250 as debounce value.

**Comment by TimLariviere** [comment] 2019-10-03 20:39
Thanks @Blener and @SergejDK. I do reproduce with your example.
I'll take a closer look where `debounce` is failing.

In the meantime, I've released an alpha version where `debounce` will no longer be necessary.
F.XF won't trigger events when updating property values internally.
It should fix the issue.

Though a little disclaimer, this version is still susceptible to have a lot of changes before final release.
I would recommend to keep a copy of your solution before testing it.

https://www.nuget.org/packages/Fabulous.XamarinForms/0.50.0-alpha

**Comment by TimLariviere** [comment] 2019-10-03 20:40
Oops, forgot the pinging.

@sandeepc24 @Blener If you have some time, could you test this 0.50.0-alpha version and remove `debounce` to check if this fixes the issue?
Thanks

**Comment by TimLariviere** [comment] 2019-10-04 18:07
With `0.50.0-alpha.2`, FabulousContacts is now running correctly without `debounce` 🎉 
https://github.com/TimLariviere/FabulousContacts/commit/5008409ed3ddaf443714086001f9a6026124566d

**Comment by TimLariviere** [comment] 2019-10-04 21:05
@SergejDK With the alpha release, your sample works correctly.

**Comment by Blener** [comment] 2019-10-07 21:03
@TimLariviere Sorry for the late response. I tested with the sample and it worked ok, but couldn't test in the app I'm developing since my views broke after I updated do alpha. Whenever I'm able to test it I'll get back to you.

Thank you.

**Comment by TimLariviere** [comment] 2019-10-27 08:45
This issue will be fixed in the coming v0.50 release.
Here's the migration guide to help you move to that version: https://fsprojects.github.io/Fabulous/Fabulous.XamarinForms/migration-guide-to-0.50.html

(If you want to "test" the migration path, you can target v0.50.0-alpha.7 for now)

**Closed by TimLariviere** 2019-10-27 08:45 UTC
Labels: a/controls, proj/xamarinforms, t/bug
